### ISSUE TITLE
conflict with scribe

### ISSUE THREAD

**Issue by ahuret** [outr/profig#115]
Hello, thank you for this nice library ! :-)

We've been using profig and scribe for two years for configuration and logging management.
Since we've updated new versions of both, we found an unexpected issue, that's looks like a conflict between the libraries.
When I create a `scribe.Logger`, then load a yaml file using profig, there is a Runtime Exception:

`Caused by: java.lang.AbstractMethodError: Receiver class profig.ProfigYaml$ does not define or inherit an implementation of the resolved method 'abstract fabric.Value apply(java.lang.String)' of interface profig.ProfigJson.` .

Here is a MRE that hit the issue:

```scala
import profig._
import scribe.handler.LogHandler

object Main extends App {
 var logger = scribe.Logger.empty.withHandler(LogHandler())
  Profig.loadFile(file = new java.io.File("/config.yaml"), errorHandler = Some(((e: Throwable) => e.asInstanceOf[RuntimeException].printStackTrace)))
}
```

I bet there is some global variable(s) shared between the libraries that could be the cause.

Thank you in advance !

**Comment by darkfrog26** [comment]
No need to cross-post, I responded here: https://github.com/outr/scribe/issues/294#issuecomment-1113607575
