### ISSUE TITLE
Support more than one configuration per JVM

### ISSUE THREAD

**Issue by ssimeonov** [outr/profig#2]
Currently, `ConfigPath` has hard-coded bindings to `Config.json` in `get()` and `combine()`. This prevents the possibility of having more than one config per JVM, which is very useful in some situations, e.g., shared Apache Spark REPL sessions in a single driver JVM.

Can we consider a change where `Config` is the global configuration, with all the automatic loading niceties, but users have the possibility of creating other configurations, independent of that? 

One possible way to formulate the problem is as follows:

1. A configuration is rooted in a mutable value that can be read & updated via a simple interface.

2. We create a base trait for `ConfigPath`'s behavior that depends on the getter/mutator API from (1), however this is done.

3. `ConfigPath` is refactored to access `Config.json` for backward compatibility reasons. 

4. Users can create their own root paths that target different configs as needed. 

Example of new functionality assuming an abstract class implementation:

```scala
abstract class ConfigPathLike(val path: List[String]) extends Serializable {
  /* rest of ConfigPath API */
  def getRoot: Json
  def setRoot(value: Json): Unit
}

class ConfigPath(override val path: List[String]) extends ConfigPathLike(path) {
  def getRoot = Config.json
  def setRoot(value: Json) = Config.json = value
}
  
class LocalConfig() extends ConfigPathLike(Nil) {
  private var json: Json = Config.json
  def getRoot = json
  def setRoot(value: Json) = json = value
}
```

An open question is whether we want to make paths from different roots be different types. I can see both pros and cons to this. For simplicity, my gut sense would be to not do this initially as this can always be added via something like `TypedConfigPathLike[A <: TypedConfigPathLike[A]]` later.

**Comment by darkfrog26** [comment]
What would you think about the ability to define sub-configs?  These would be unique instances of `Config` and could have a parent config.  `object Config` would be the default parent for all sub-configs, but you could change or load unique settings for each of them.  Would that fulfill your need?

**Comment by ssimeonov** [comment]
Yes, it would.

**Comment by darkfrog26** [comment]
I added another ticket for that: https://github.com/outr/profig/issues/3

**Comment by darkfrog26** [comment]
Technically it is possible by modifying the level above that path and removing that field from the JSON, but that's not at all convenient.

**Comment by darkfrog26** [comment]
I created a milestone of new functionality I should have incorporated by Monday and added this to the list: https://github.com/outr/profig/milestone/1

**Comment by ssimeonov** [comment]
👍

**Comment by darkfrog26** [comment]
Feel free to offer any additional features or feedback on the other issues in this milestone.
