### ISSUE TITLE
ProfigLookupPath.propertiesString2Json does not recognize a property if its value contains an equal sign

### ISSUE THREAD

**Issue by marcelrf** [outr/profig#24]
If there's a property file with a property like:
`some_regex = .*/year=[0-9]{4}/month=[0-9]{2}/day=[0-9]{2}/.*`

Then ProfigLookupPath.propertiesString2Json (line 109) will split this property using:
`private val EqualsProperty = """(.+)=(.+)""".r` (line 93)

Which will result in:
key = `some_regex = .*/year=[0-9]{4}/month=[0-9]{2}/day`
value = `[0-9]{2}/.*`

Because the first (.+) of EqualsProperty is greedy and tries to match as much as possible, thus using the last equals sign (=) to split the property into invalid key and value.

Maybe, a solution could be making the first (.+) of EqualsProperty lazy by adding a question mark:
`private val EqualsProperty = """(.+?)=(.+)""".r`
This way the property would be split at the first equal sign, as opposed of the last.

**Comment by darkfrog26** [comment]
Very good catch.  Would you mind submitting a PR to fix this?  Otherwise, I'll try to get to it as soon as I can. Thanks.

**Comment by marcelrf** [comment]
Thanks for your prompt response!
I submitted a PR with the change.
Cheers

**Comment by darkfrog26** [comment]
Awesome, merged!  Thanks!  Any rush to get this into a release build?

**Comment by marcelrf** [comment]
Thanks for the quick merge!
Well, if it's not a lot of work or confusion for you, we'd appreciate if you do a release build.
Otherwise, we can workaround the problem until the release comes.

**Comment by darkfrog26** [comment]
This has been released with `2.3.3`
