### ISSUE TITLE
Re-enable hocon support for scala 2.13 ?

### ISSUE THREAD

**Issue by vdebergue** [outr/profig#30]
Hello,

I just started using the library as it looked to fit really well my needs but then I noticed that the hocon support was disabled (https://github.com/outr/profig/commit/a1521509a74d87fd9a92473e4e5bbf7e81ba5e25). 

Is there something to do to have hocon supported with scala 2.13 ?

**Comment by darkfrog26** [comment]
I should have a 3.0 release out this week that makes some major changes and re-introduces the support in a better way.

**Comment by darkfrog26** [comment]
Just released 3.0 with new support including updated README
